spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1qaz
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    mode: HTML5
    cache: false
    
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations:
  - /mapper/*.xml  
